<a href="https://colab.research.google.com/github/MarcGaac/FA/blob/main/FA5_GAAC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

P-5.32 Write a Python function that takes two three-dimensional numeric data
sets and adds them componentwise.

In [ ]:
import numpy as np

def add_3d_datasets(dataset1, dataset2):
    """
    Adds two three-dimensional numeric datasets component-wise.

    Parameters:
    dataset1 (np.ndarray): First 3D dataset.
    dataset2 (np.ndarray): Second 3D dataset.

    Returns:
    np.ndarray: Resultant 3D dataset after component-wise addition.

    Raises:
    ValueError: If the input datasets do not have the same shape.
    """
    # Convert inputs to numpy arrays
    array1 = np.array(dataset1)
    array2 = np.array(dataset2)

    # Check if the shapes of the datasets are the same
    if array1.shape != array2.shape:
        raise ValueError("Input datasets must have the same shape.")

    # Add the datasets component-wise
    result = array1 + array2

    return result

# Example usage:
dataset1 = np.random.rand(3, 3, 3)  # A random 3D dataset
dataset2 = np.random.rand(3, 3, 3)  # Another random 3D dataset

result = add_3d_datasets(dataset1, dataset2)
print("Dataset 1:\n", dataset1)
print("Dataset 2:\n", dataset2)
print("Resultant Dataset:\n", result)

Dataset 1:
 [[[0.11811191 0.03657292 0.74026586]
  [0.38407457 0.99491611 0.28874713]
  [0.335661   0.39763628 0.52559526]]

 [[0.41810076 0.766138   0.3334093 ]
  [0.15403295 0.49644746 0.65050847]
  [0.13119872 0.11356236 0.1829569 ]]

 [[0.32317086 0.42030646 0.39570181]
  [0.9059322  0.05147894 0.21310241]
  [0.88896069 0.50507446 0.07375128]]]
Dataset 2:
 [[[0.64983246 0.90038761 0.76626006]
  [0.6739143  0.64715638 0.56028339]
  [0.98165861 0.16829569 0.80579971]]

 [[0.20404691 0.87422873 0.67249362]
  [0.6338851  0.45744297 0.94945339]
  [0.87696711 0.81776119 0.27736453]]

 [[0.1249526  0.41318916 0.91239129]
  [0.76444895 0.2088452  0.03571767]
  [0.42716073 0.020083   0.65540428]]]
Resultant Dataset:
 [[[0.76794438 0.93696053 1.50652592]
  [1.05798888 1.64207249 0.84903052]
  [1.31731961 0.56593197 1.33139497]]

 [[0.62214767 1.64036673 1.00590292]
  [0.78791805 0.95389042 1.59996186]
  [1.00816583 0.93132355 0.46032143]]

 [[0.44812346 0.83349561 1.3080931 ]
  [1.67038115 0

Give a complete ArrayDeque implementation of the double-ended queue
ADT as sketched in Section 6.3.2.

In [ ]:
class ArrayDeque:
    def __init__(self):
        """Initialize an empty deque."""
        self.data = [None] * 10  # Initial capacity
        self.size = 0
        self.front = 0

    def is_empty(self):
        """Check if the deque is empty."""
        return self.size == 0

    def __len__(self):
        """Return the number of elements in the deque."""
        return self.size

    def first(self):
        """Return the first element of the deque."""
        if self.is_empty():
            raise IndexError("Deque is empty")
        return self.data[self.front]

    def last(self):
        """Return the last element of the deque."""
        if self.is_empty():
            raise IndexError("Deque is empty")
        back = (self.front + self.size - 1) % len(self.data)
        return self.data[back]

    def add_first(self, item):
        """Add an element to the front of the deque."""
        if self.size == len(self.data):
            self.resize(2 * len(self.data))  # Double the array size
        self.front = (self.front - 1) % len(self.data)
        self.data[self.front] = item
        self.size += 1

    def add_last(self, item):
        """Add an element to the back of the deque."""
        if self.size == len(self.data):
            self.resize(2 * len(self.data))  # Double the array size
        back = (self.front + self.size) % len(self.data)
        self.data[back] = item
        self.size += 1

    def delete_first(self):
        """Remove and return the first element of the deque."""
        if self.is_empty():
            raise IndexError("Deque is empty")
        item = self.data[self.front]
        self.data[self.front] = None  # Clear the slot
        self.front = (self.front + 1) % len(self.data)
        self.size -= 1
        return item

    def delete_last(self):
        """Remove and return the last element of the deque."""
        if self.is_empty():
            raise IndexError("Deque is empty")
        back = (self.front + self.size - 1) % len(self.data)
        item = self.data[back]
        self.data[back] = None  # Clear the slot
        self.size -= 1
        return item

    def resize(self, new_capacity):
        """Resize the underlying array to a new capacity."""
        new_data = [None] * new_capacity
        for i in range(self.size):
            new_data[i] = self.data[(self.front + i) % len(self.data)]
        self.data = new_data
        self.front = 0  # Reset front to the beginning of the new array

# Example usage
if __name__ == "__main__":
    deque = ArrayDeque()
    deque.add_last(1)
    deque.add_last(2)
    deque.add_first(0)
    print("First:", deque.first())  # Output: First: 0
    print("Last:", deque.last())    # Output: Last: 2
    print("Deleted First:", deque.delete_first())  # Output: Deleted First: 0
    print("Deleted Last:", deque.delete_last())    # Output: Deleted Last: 2
    print("Size:", len(deque))  # Output: Size: 1

First: 0
Last: 2
Deleted First: 0
Deleted Last: 2
Size: 1
